# This workflow runs on commit to build Iris Client and server

name: Build_Iris

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, master, dev, test, Brighton ]
  pull_request:
    branches: [ main, master, dev, test ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
		with:
          msbuild-architecture: Any CPU
      - name: Build Iris Server for release
        run: msbuild src\server\Iris-Server.csproj.csproj -t:rebuild -verbosity:diag -property:Configuration=Release
      - name: Build Iris Client for release
        run: msbuild src\server\Iris-Client.csproj.csproj -t:rebuild -verbosity:diag -property:Configuration=Release
