name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ Brighton ]
  #pull_request:
  #  branches: [ main, master, dev, test ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:  
  build:    
    runs-on: windows-latest
    
    steps:      
      - uses: actions/checkout@v3

      - name: bump version and push 
        id: bump_tag
        #uses: anothrnick/github-tag-action@1.36.0
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.github_token }}
          default_bump: patch
          default_prerelease_bump: prerelease
          tag_prefix: v
          release_branches: master,main,Brighton
          create_annotated_tag: false
          fetch_all_tags: false
          dry_run: false

      - name: New Version Number
        run: |
          echo "The version of this installer will be ${ steps.tag_version.outputs.new_tag }."
          echo "The version of this installer will be ${{ steps.tag_version.outputs.new_tag }} ."
          echo 'The version of this installer will be ${{ steps.tag_version.outputs.new_tag }} .'
          echo 'The version of this installer will be ${ steps.tag_version.outputs.new_tag } .'
          echo 'The version of this installer will be $ steps.tag_version.outputs.new_tag  .'

      # - name: Bump version and push tag
        # uses: laputansoft/github-tag-action@v4.6
        # with:
          # github_token: ${{ secrets.GITHUB_TOKEN }}
          # tag: ${{ steps.package-version.outputs.version }}
 
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Setup VS Dev Environment
        uses: seanmiddleditch/gha-setup-vsdevenv@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      # - name: Restore Packages
      #   run: nuget restore "src/Iris Screen Exporter.sln"

      - name: Disable Out of Process Building
        run: .\DisableOutOfProcBuild.exe
        working-directory: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\VSI\DisableOutOfProcBuild

      - name: Build Solution
        run: |
          msbuild.exe "src/Iris Screen Exporter.sln" /p:platform="x64" /p:configuration="NoInstallers"

      - name: Build the Installer
        run: DevEnv "src/Iris Screen Exporter.sln" /build "JustInstallers|x64"

      - name: Rename the Installer
        run: |
          echo "The version of this installer will be ${ steps.tag_version.outputs.new_tag } ."
          mv "Installer/Iris Setup/JustInstallers/Iris Setup.msi" "Installer/Iris Setup/JustInstallers/Iris_Screen_Exporter_${ steps.tag_version.outputs.new_tag }.msi"

      - uses: actions/upload-artifact@v3
        with:
          name: Iris Screen Exporter Installer
          path: "Installer/Iris Setup/JustInstallers/Iris_Screen_Exporter_${ steps.tag_version.outputs.new_tag }.msi"
          retention-days: 2
